const usersData = {
  admin: {
    "medhat@gmail.com": {
      role: "admin",
      username: "medhat",
      email: "medhat@gmail.com",
      password: "medhat@2024",
      userProfileImage: "",
      phone: "01011123795",
      accountstate: "Active",
      inbox: [],
    },
  },
  customers: {
    "belalnagy@gmail.com": {
      role: "customer",
      username: "belal",
      email: "belalnagy@gmail.com",
      password: "belal@2024",
      address: "",
      userProfileImage: "",
      phone: "01527941976",
      accountstate: "Active",
      cart: [],
      wishlist: [],
      inbox: [],
      orders_history: [],
    },
    "sara@gmail.com": {
      role: "customer",
      username: "sara",
      email: "sara@gmail.com",
      password: "sara@2025",
      accountstate: "Active",
      address: "",
      userProfileImage: "",
      phone: "01120647390",
      cart: [],
      wishlist: [],
      inbox: [],
      orders_history: [],
    },
    "amir@gmail.com": {
      role: "customer",
      username: "amir",
      email: "amir@gmail.com",
      password: "amir@2025",
      accountstate: "Active",
      address: "",
      userProfileImage: "",
      phone: "01100743907",
      cart: [],
      wishlist: [],
      inbox: [],
      orders_history: [],
    },
  },
  sellers: {
    "ahmed@gmail.com": {
      role: "seller",
      username: "ahmed",
      email: "ahmed@gmail.com",
      password: "ahmed@2025",
      accountstate: "Active",
      userProfileImage: "",
      phone: "01224803257",
      // inbox: [],
    },
    "mariam@gmail.com": {
      role: "seller",
      username: "mariam",
      email: "mariam@gmail.com",
      password: "mariam@2025",
      accountstate: "Suspended",
      userProfileImage: "",
      phone: "01020646624",
      // inbox: [],
    },
  },
};

export { usersData };
